version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/app
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build: ./backend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=chatdb
